# 站点的基本信息配置
site_name: 直播电视文档 
site_url: https://zbds.top  
copyright: Copyright &copy; www.zbds.top 
site_description: "直播电视文档 "
extra:
  generator: false  # 关闭页脚的“Made with Material for MkDocs”显示
  footer: '直播电视文档'  
  comments:
    enabled: false
  use_directory_urls: false

extra_javascript:
  - 'js/google_ads.js'

theme:
  name: material 
  custom_dir: overrides
  language: zh
  favicon: assets/favicon.png  

  features:  # 启用主题的一些特性和功能
    - navigation.path  # 在导航栏中显示当前页面的完整路径
    - navigation.sections  # 在侧边栏中显示各部分的结构化导航
    - navigation.top  # 在顶部显示返回顶部的按钮
    - navigation.instant  # 启用即时导航，无需页面刷新
    - navigation.instant.progress  # 在即时导航时显示加载进度条
    - navigation.prune  # 只显示与当前页面相关的导航项，减少干扰
    - toc.follow # 滚动的时候侧边栏自动跟随
    - navigation.instant # 现在页面不会跳转,而是类似单页应用,搜索和各种跳转都是在当前页面完成,对美观有很大帮助
    #- navigation.tabs # 页面上方的标签页
    - navigation.tracking # 页面滚动时，导航栏高亮当前页面
    - navigation.sections # 使导航栏分块
    - navigation.expand # 默认展开导航
    - navigation.footer # 页脚提示下一章
    - search.suggest  # 启用搜索建议功能，用户输入时显示建议结果
    - search.highlight # 搜索结果高亮
    - search.share # 搜索结果分享
    - content.code.copy # 代码段上的赋值按钮
  
  
# 导航栏的配置，定义站点顶部和侧边栏的导航结构
nav:
  - 首页: index.md  
  
  - 安装:  
      - 安装教程: jiaocheng/index.md
      - 电视安装: aztv.md
      - 手机安装: azsj.md
  - 视频演示: spys.md  
  - 使用须知: syxz.md  
  - 使用说明: sysm.md
  - VIP定制: vipdingzhi.md  
  - 集锦:    
      - 网络科普: wlkp.md
      #- 常见问题: cjwt.md  
      - 常见问题: cjwt.md
  - 软件图例: newtl.md  
  - 打赏说明: dssm.md  
  - 免费版: about.md 
  - 转换工具: tools.md