# 站点的基本信息配置
site_name: 直播电视文档 
site_url: https://zbds.zhoujie218.top  

# 主题和样式配置
theme:
  name: material 
  features:  # 启用主题的一些特性和功能
    - navigation.path  # 在导航栏中显示当前页面的完整路径
    - navigation.sections  # 在侧边栏中显示各部分的结构化导航
    - navigation.top  # 在顶部显示返回顶部的按钮
    - navigation.instant  # 启用即时导航，无需页面刷新
    - navigation.instant.progress  # 在即时导航时显示加载进度条
    #- navigation.prune  # 只显示与当前页面相关的导航项，减少干扰
    - navigation.footer  # 在页面底部显示页脚
    - search.suggest  # 启用搜索建议功能，用户输入时显示建议结果
  
  favicon: assets/favicon.png  



  custom_dir: overrides
  extra_css:
    - overrides/main.css

# 导航栏的配置，定义站点顶部和侧边栏的导航结构
nav:
  - 首页: index.md  
  
  - 下载安装:  
      - 手机安装: azsj.md  
      - 电视安装: aztv.md  
  - 视频演示: spys.md  
  - 使用须知: syxz.md  
  - 使用说明: sysm.md  
  - 网络科普: wlkp.md  
  - 图例: newtl.md  
  - 打赏说明: dssm.md  
  - 免费版: about.md  